# KmeansForCone action
string image_topic_name
----
# Result
bool cone_found
uint8 alow_hue
uint8 ahigh_hue
uint8 alow_saturation
uint8 ahigh_saturation
uint8 alow_value
uint8 ahigh_value
----
# Feedback
string feedback